# SQL Server Command Line Tools
#https://github.com/microsoft/mssql-docker/blob/master/linux/mssql-tools/Dockerfile
#docker build -f Dockerfile_client -t mysql:v1 .
#docker run -it mysql:v1
#sqlcmd -S 192.168.253.125 -U sa -P '1qazxxxx'
#SELECT Name from sys.Databases
#go
#可以参考上一篇中的步骤，将项目部署至ubuntu系统中。这里需要注意的是，如果你其他功能访问正常，但连接数据库时出错（通过supervisor配置的输出日志/var/log/youapp.out.log 查看错误），检查你的数据库版本。需要SQL Server2008R2 sp3版本以上才可以，如果你时sql server 2008R2，可以通过下面连接下载补丁包安装，完成后重启sqlserver服务即可。
#补丁下载：https://www.microsoft.com/en-us/download/details.aspx?id=44271
FROM ubuntu:16.04

LABEL maintainer="SQL Server Engineering Team"

# apt-get and system utilities
RUN apt-get update && apt-get install -y \
	curl apt-transport-https debconf-utils \
    && rm -rf /var/lib/apt/lists/*

# adding custom MS repository
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
RUN curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list > /etc/apt/sources.list.d/mssql-release.list

# install SQL Server drivers and tools
RUN apt-get update && ACCEPT_EULA=Y apt-get install -y msodbcsql mssql-tools
RUN echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
RUN /bin/bash -c "source ~/.bashrc"



RUN apt-get -y install locales
RUN locale-gen en_US.UTF-8
RUN update-locale LANG=en_US.UTF-8



CMD /bin/bash