FROM alpine:3.6
ARG user=root1
#RUN useradd -s /bin/bash $user
#RUN adduser --disabled-password --gecos '' $user
RUN adduser -D -g '' $user
USER $user

RUN echo 'aaaa'
#docker build --build-arg user=banana .
# https://blog.51cto.com/9486329/2178589?source=dra  ---no test
